version: "3"

services:
  redis-cache:
    image: redis
    container_name: redis
    restart: on-failure
    ports:
      - 10002:6379
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    network_mode: bridge
volumes:
  redis-data:
networks:
  default:
    external:
      name: docker-dev-network
